{% set name = "blacktex" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blacktex-{{ version }}.tar.gz
  sha256: 8cb9d717a95ed90410bd643c03a9fb3748f8491cd010cece695017014bfa7722

build:
  number: 0
  noarch: python
  entry_points:
    - blacktex = blacktex.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=3.2,<4
  run:
    - python >=3.6
    - importlib-metadata

test:
  imports:
    - blacktex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/blacktex
  summary: Cleans up your LaTeX files
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    `blacktex` is a little tool, helping with the article editing 
    for LaTeX. It removes all comments from a given file and corrects 
    some common anti-patterns.

    PyPI: [https://pypi.org/project/blacktex/](https://pypi.org/project/blacktex/)

  doc_url: https://github.com/nschloe/blacktex
  dev_url: https://github.com/nschloe/blacktex

extra:
  recipe-maintainers:
    - sugatoray
